pdfparser/pdfparser/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('start.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdfparser/start/urls.py
from django.conf.urls import url
from start import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'start'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

pdfparser/start/models.py
from django.db import models


class UserPDF(models.Model):
    pdf = models.FileField('Upload Resumes', upload_to='UploadedPDFs/')
    title = models.CharField(max_length=1000, default="")
    tables = models.IntegerField(blank=True, default=0)
    pages = models.IntegerField(blank=True, default=0)

pdfparser/start/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField(label='', widget=forms.FileInput(
        attrs={}))

pdfparser/start/views.py
import os
import zipfile
import re
import PyPDF2
import camelot
from django.shortcuts import render

from pdfrw import PdfReader

from start.forms import UploadFileForm
from start.models import UserPDF

try:
    from xml.etree.cElementTree import XML
except ImportError:
    from xml.etree.ElementTree import XML

WORD_NAMESPACE = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
PARA = WORD_NAMESPACE + 'p'
TEXT = WORD_NAMESPACE + 't'


def convertpdf(name):
    # print("test")
    pdfobj = open("UploadedPDFs/" + str(name), 'rb')
    pdfreader = PyPDF2.PdfFileReader(pdfobj)
    # print(pdfreader.numPages)
    x = name[0:len(name) - 3]
    desturl = str(x) + "txt"
    fob = open("UploadedPDFs/" + desturl, "w", encoding="utf-8")
    for page in pdfreader.pages:
        s = page.extractText()
        # print(s)
        lines = s.split("\n")
        # print(lines)
        for line in lines:
            fob.write((line + "\n"))

    fob.close()
    pdfobj.close()


def index(request):
    if request.method == "POST":
        uploadform = UploadFileForm(request.POST, request.FILES)
        if uploadform.is_valid():
            # saving the file
            file = request.FILES['file']

            pdf_file = UserPDF(pdf=file)
            pdf_file.save()

            print(file.name)
            print(file.content_type)

            f = os.path.join('pdfparser', 'UploadedPDFs', file.name)

            pdfobj = open(f, 'rb')
            pdfreader = PyPDF2.PdfFileReader(pdfobj)
            pages = pdfreader.numPages
            tables = extractnotables(f)
            title = extracttitle(f)

            user = UserPDF(title=title, tables=tables, pages=pages, pdf=file)

            user.save()
            return render(request, 'index.html',
                          {'fileform': UploadFileForm(),
                           'files': UserPDF.objects.all()})
    else:
        print("default form created")
        form = UploadFileForm()
        return render(request, 'index.html',
                      {'fileform': form,
                       'files': UserPDF.objects.all()})


# nombre de table
def extractnotables(resume):
    tables = camelot.read_pdf(resume)
    notables = tables.n

    return notables


# pdf title
def extracttitle(file):
    # Extract pdf title from pdf file
    title = PdfReader(file).Info.Title
    # Remove surrounding brackets that some pdf titles have
    if title:
        title = title.strip('()')
    else:
        title = ""
    return title

pdfparser/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" type="text/css"
          media="all"/>

    <title>{% block title %}{% endblock %}</title>
</head>
<body style="font-family: 'Poppins', sans-serif;">
{% include 'navbar.html' %}

<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h2 style="text-align: center">your pdf has been uploaded</h2>
            <h3 style="text-align: center">and all the details are uploaded to database successfully...</h3>

            <button id="uploadMoreBtn" class="btn btn-info" style="margin-bottom: 10px; border-radius: 0;">
                Upload another file
            </button>

            <div style="align-items: center;text-align: center;display: none" id="fileForm">
                <form enctype="multipart/form-data" class="form pt-2 pb-3"
                      action="{% url 'start:index' %}" method="POST" style="padding-left: 100px; ">

                    {% csrf_token %}
                    <div class="row">
                        <div class="col-3"></div>
                        <div class="col-4 d-flex justify-content-end">
                            {{ fileform }}
                        </div>
                        <div class="col-2 pull-left">
                            <input class="btn btn-success" type="submit" value="Submit"/>
                        </div>
                        <div class="col-3"></div>
                    </div>

                </form>
            </div>

            <!-- <a href="">

             </a>-->
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <table class="table table-bordered table-striped table-responsive">
                <thead>
                <tr>
                    <th>#</th>
                    <th>title</th>
                    <th>link</th>
                    <th>Number of pages</th>
                    <th>Number of tables</th>
                </tr>
                </thead>
                <tbody>
                {% for file in files %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ file.title }} </td>
                        {% if file.pdf %}
                            <td>
                                <a href="media/{{ file.pdf }}" target="_blank">
                                    <i class="fa fa-eye pr-1"> voir</i>
                                </a>
                            </td>
                        {% else %}
                            <td>------</td>
                        {% endif %}
                        <!--<td><a href="{{ pdf.url }}" target="_blank">{{ pdf.url }}</a></td>-->
                        <td>{{ file.pages }}</td>
                        <td>{{ file.tables }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#uploadMoreBtn").click(function () {

            // check paragraph once toggle effect is completed
            if ($("#fileForm").is(":visible")) {
                $('#fileForm').hide();
            } else {
                $('#fileForm').show();
            }
        });
    });
</script>
</body>
</html>

pdfparser/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark sidebarNavigation" data-sidebarClass="navbar-dark bg-dark">
    <a class="navbar-brand" href="">
       my pdf Parser :)
    </a>
    <button class="navbar-toggler leftNavbarToggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>